services:
  - type: web
    name: activelife-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    rootDir: backend
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: EMAIL_SENDER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: FAST2SMS_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: SECRET_KEY
        sync: false
