from utils.db import db
from datetime import datetime

class AIPlan:
    @staticmethod
    def get_collection():
        if db is None:
            raise RuntimeError("Database connection is not established! Please check your MONGO_URI in environment variables and verify that MongoDB Atlas allows access from all IPs (0.0.0.0/0).")
        return db['ai_plans']

    @staticmethod
    def save_plan(user_id, plan_type, content):
        plan_data = {
            "user_id": str(user_id),
            "plan_type": plan_type, # 'workout' or 'diet'
            "content": content,     # The markdown/text generated by AI
            "created_at": datetime.utcnow()
        }
        return AIPlan.get_collection().insert_one(plan_data)

    @staticmethod
    def get_latest_plan(user_id):
        return AIPlan.get_collection().find_one(
            {"user_id": str(user_id)},
            sort=[("created_at", -1)]
        )

    @staticmethod
    def get_plans_by_type(user_id):
        plans = {}
        for p_type in ['diet', 'workout']:
            plan = AIPlan.get_collection().find_one(
                {"user_id": str(user_id), "plan_type": p_type},
                sort=[("created_at", -1)]
            )
            if plan:
                plan['_id'] = str(plan['_id'])
                plans[p_type] = plan
        return plans

    # ─── Structured Workout Plan (for MyWorkout page) ──────────────────────────

    @staticmethod
    def save_workout_plan(user_id, structured_plan):
        """
        Upsert the structured workout plan for a user.
        Replaces the previous plan entirely — no duplicates.
        structured_plan is the parsed JSON dict: { explanation, plan: [...] }
        """
        AIPlan.get_collection().update_one(
            {"user_id": str(user_id), "plan_type": "structured_workout"},
            {
                "$set": {
                    "user_id": str(user_id),
                    "plan_type": "structured_workout",
                    "structured_plan": structured_plan,
                    "created_at": datetime.utcnow()
                }
            },
            upsert=True
        )

    @staticmethod
    def get_workout_plan(user_id):
        """
        Returns the latest structured workout plan for a user, or None.
        """
        doc = AIPlan.get_collection().find_one(
            {"user_id": str(user_id), "plan_type": "structured_workout"},
            sort=[("created_at", -1)]
        )
        if doc:
            doc['_id'] = str(doc['_id'])
            return doc.get("structured_plan")
        return None